name: learn-github-action
on:
  push:
    branches: [main]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v10.19.0]
    steps:
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
      - name: install npm
        run: |
          npm install
      - name: install gh-pages
        run: |
          npm install gh-pages --save-dev
      - name: run deploy command
        run: |
          npm run deploy

      # - uses: peter-evans/dockerhub-description@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #     repository: ${{env.repo}}
